### ISSUE TITLE
about Steamlauncher.exe

### ISSUE THREAD

**Issue by Mainak009** [Jack-Myth/Threshold-Miku#90]
is there any way of ditching the Steamlauncher?...it's a little annoying for regular users when restarting steam or starting steam after a PC reboot.

**Comment by Gensokyo1995** [comment]
A steam shortcut will be created when setting Threshold Miku Customizer 2
![image](https://user-images.githubusercontent.com/43993884/216795642-b7c8fda0-c217-4ef4-bb46-baf038c768ed.png)
you can use that restarting steam

**Comment by Mainak009** [comment]
I know but that's confusing too as there's 2 shortcuts of steam.... please make something that won't require this launcher and will work only with normal opening of steam like before.

**Comment by RS96C** [comment]
you can delete the steam shortcut and keep the one created by Threshold Miku Customizer 2
its doesn't affect the use

**Comment by RS96C** [comment]
You can delete the steam shortcut
its doesn't affect the use
If you want personalization, this is inevitable

**Comment by RS96C** [comment]
![image](https://user-images.githubusercontent.com/87936721/218267838-ca16c941-e0ce-485d-a53d-2110fa5c3ce4.png)

**Comment by Mainak009** [comment]
> You can delete the steam shortcut
> its doesn't affect the use
> If you want personalization, this is inevitable

But why is this required now?.... before not required 🤔

**Comment by Jack-Myth** [comment]
Since Steam update it's client, the webkit.css can't take effect any longer.  The problem can be solved by doing a little modification of steam.  But when Steam startup normally, it will check all files and revert them to default.  So it need "-noverifyfiles" argument to disable the file validation.  That is what the Launcher did.  As for now, I still not find a way to inject webkit.css to steam without doing all these things.  If you find any solution,  please let me know.
If you want to know the implementation of SteamLauncher.exe, [check the sourcecode here](https://github.com/Jack-Myth/Threshold-Miku-Customizer-2/blob/master/SteamLauncher4ThresholdMiku/Program.cs), It's simple, but it's necessary.

**Comment by Mainak009** [comment]
> Since Steam update it's client, the webkit.css can't take effect any longer.  The problem can be solved by doing a little modification of steam.  But when Steam startup normally, it will check all files and revert them to default.  So it need "-noverifyfiles" argument to disable the file validation.  That is what the Launcher did.  As for now, I still not find a way to inject webkit.css to steam without doing all these things.  If you find any solution,  please let me know.
> If you want to know the implementation of SteamLauncher.exe, [check the sourcecode here](https://github.com/Jack-Myth/Threshold-Miku-Customizer-2/blob/master/SteamLauncher4ThresholdMiku/Program.cs), It's simple, but it's necessary.

Okay thanks for explaining but there is one problem with startup.... when steam open normally then have to exit and open with launcher 🙁

**Comment by Jack-Myth** [comment]
> 

You can disable autostart in steam settings. Then create a shortcut of SteamLauncher and copy it to "%ProgramData%\Microsoft\Windows\Start Menu\Programs\StartUp"

**Comment by Mainak009** [comment]
> > 
> 
> You can disable autostart in steam settings. Then create a shortcut of SteamLauncher and copy it to "%ProgramData%\Microsoft\Windows\Start Menu\Programs\StartUp"

Yeah too much work for a simple thing... I would rather disable the theme 😪
